### ISSUE TITLE
vpn-server-api-stats needs >= 128 MB

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-server-api#73]
On one of our instances, the stats scripts needs more than 128 MB of memory. Clearly a memory leak of some kind!

**Comment by fkooman** [comment]
`src/Stats.php`

**Comment by fkooman** [comment]
```
sqlite> select count(*) from connection_log;
73495
sqlite>
```

We have ~ 70k connections in the log table.

**Comment by fkooman** [comment]
Hmm that's about 1800 bytes / per entry in memory. That doesn't sound too bad... Not nearly as bad as I imagined...

**Comment by fkooman** [comment]
The quick fix is to of course set the available memory to PHP to 256 MB (for PHP cli in `/etc/php.ini`)

**Comment by ghost** [comment]
https://github.com/eduvpn/vpn-user-portal/commit/1dc6b0d23145a4ac7d4a3c5eee25f54848daa014

**Comment by ghost** [comment]
We have the fix right here! Now only we need to apply it to the `v2` branch!

**Comment by ghost** [comment]
Currently on one of the servers: 

```
sqlite> select count(*) from connection_log;
212939
sqlite> 
```

**Comment by ghost** [comment]
Fixed in 2.2.2, release 2020-05-12.

**Comment by ghost** [comment]
*still* not fixed unfortunately... should have really tested it with big dataset.

**Comment by ghost** [comment]
Will be completely redone in 3.x
