### ISSUE TITLE
API endpoint answers with error 500 on invalid JWT token

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-server-api#75]
EduVPN 1.0 uses the same API as 2.0, but they use different tokens. The API server fails with error 500, so the client never knows that it should toss its key material.

Follow up from https://github.com/eduvpn/macos/issues/217

**Comment by ghost** [comment]
this is actually in vpn-user-portal.

**Comment by ghost** [comment]
https://github.com/eduvpn/vpn-user-portal/commit/dd2759793ceaf15b0b93cf7cc1b1f1c0d27e2e9e
