### ISSUE TITLE
Write VPN connect/disconnect information to syslogd

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/vpn-server-api#84]
Some would like to use syslog to send logging to remote logging servers. Therefore it would be nice to have eduVPN write logging to syslog to make this possible. Atleast UserID and VPN IP given when someone connects and disconnects to the VPN should be logged.

**Comment by ghost** [comment]
Currently only the CN is logged (as part of OpenVPN server logging) and not the user_id. The VPN IPs are indirectly also logged in the OpenVPN log. 

I think for production servers OpenVPN logging should not be on at all...

**Comment by ghost** [comment]
> I think for production servers OpenVPN logging should not be on at all...

So the user ID + VPN IPs should be logged _independently_ of the OpenVPN server logging.

Currently the eduVPN logging only happens in the database, not exposed to journald / syslog.

**Comment by ghost** [comment]
Implemented in 2.2.11 (2021-07-13)
